# Generated by Django 3.0.6 on 2020-05-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('hire_date', models.DateField(blank=True, db_column='Hire_date', null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('commision_pct', models.FloatField(blank=True, null=True)),
                ('manager_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('job_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
    ]
